const FoodArray = [
  {
    category_id: 1,
    category_name: "Canned Goods",
    foods: [
      {
        food_id: 101,
        food_name: "Brisket Spread",
        size: 1,
        weight: 115,
        energy: 200,
        water: 25,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["pate", "meats", "cans"],
      },
      {
        food_id: 102,
        food_name: "Canned Bacon",
        size: 4,
        weight: 280,
        energy: 300,
        water: 50,
        stomach: 2,
        locations: "Military bases/camps",
        searchterms: ["cans", "meats"],
      },
      {
        food_id: 103,
        food_name: "Canned Baked Beans",
        size: 4,
        weight: 455,
        energy: 200,
        water: 50,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["cans", "vegetables", "veggies"],
      },
      {
        food_id: 104,
        food_name: "Canned Peaches",
        size: 4,
        weight: 465,
        energy: 150,
        water: 100,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["cans", "fruits"],
      },
      {
        food_id: 105,
        food_name: "Canned Sardines",
        size: 2,
        weight: 125,
        energy: 250,
        water: 200,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["cans", "fishes"],
      },
      {
        food_id: 106,
        food_name: "Canned Spaghetti",
        size: 4,
        weight: 465,
        energy: 175,
        water: 75,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["cans"],
      },
      {
        food_id: 107,
        food_name: "Canned Tuna",
        size: 2,
        weight: 265,
        energy: 150,
        water: 100,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["cans", "fishes"],
      },
      {
        food_id: 108,
        food_name: "Canned Pork",
        size: 2,
        weight: 250,
        energy: 225,
        water: 25,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["cans", "meats"],
      },
      {
        food_id: 109,
        food_name: "Cat Food Can",
        size: 2,
        weight: 250,
        energy: 125,
        water: 125,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["cans", "meats"],
      },
      {
        food_id: 110,
        food_name: "Dog Food Can",
        size: 2,
        weight: 250,
        energy: 150,
        water: 100,
        stomach: 10,
        locations: "Civilian",
        searchterms: ["cans", "meats"],
      },
      {
        food_id: 111,
        food_name: "Lunchmeat",
        size: 2,
        weight: 250,
        energy: 200,
        water: 50,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["cans", "meats"],
      },
      {
        food_id: 112,
        food_name: "Strawberry Jam",
        size: 4,
        weight: 400,
        energy: 150,
        water: 50,
        stomach: 4,
        locations: "Houses",
        searchterms: ["berry", "fruits"],
      },
      {
        food_id: 113,
        food_name: "Honey",
        size: 4,
        weight: 400,
        energy: 250,
        water: 0,
        stomach: 5,
        locations: "Civilian",
        searchterms: [],
      },
      {
        food_id: 114,
        food_name: "Liver Pate",
        size: 1,
        weight: 115,
        energy: 250,
        water: 25,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["pate", "meats"],
      },
      {
        food_id: 115,
        food_name: "Pájka",
        size: 1,
        weight: 115,
        energy: 150,
        water: 25,
        stomach: 2,
        locations: "Civilian",
        searchterms: ["pajka", "pate", "meats"],
      },
      {
        food_id: 116,
        food_name: "Unknown Food Can",
        size: 4,
        weight: 400,
        energy: 200,
        water: 100,
        stomach: 10,
        locations: "Civilian",
        searchterms: ["cans"],
      },
    ],
  },
  {
    category_id: 2,
    category_name: "Dry Goods",
    foods: [
      {
        food_id: 201,
        food_name: "Cereals",
        size: 9,
        weight: 250,
        energy: 400,
        water: 0,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["dry goods"],
      },
      {
        food_id: 202,
        food_name: "Chips",
        size: 4,
        weight: 50,
        energy: 200,
        water: 0,
        stomach: 3,
        locations: "Civilian",
        searchterms: ["dry goods"],
      },
      {
        food_id: 203,
        food_name: "Crackers",
        size: 4,
        weight: 50,
        energy: 150,
        water: 0,
        stomach: 3,
        locations: "Civilian",
        searchterms: ["dry goods"],
      },
      {
        food_id: 204,
        food_name: "Rice",
        size: 6,
        weight: 500,
        energy: 100,
        water: 0,
        stomach: 3,
        locations: "All Locations",
        searchterms: ["dry goods"],
      },
      {
        food_id: 205,
        food_name: "Powdered Milk",
        size: 2,
        weight: 200,
        energy: 400,
        water: 0,
        stomach: 2,
        locations: "All Locations",
        searchterms: ["dairy", "dry goods"],
      },
      {
        food_id: 206,
        food_name: "Salty Sticks",
        size: 4,
        weight: 50,
        energy: 100,
        water: 0,
        stomach: 3,
        locations: "Civilian",
        searchterms: ["dry goods"],
      },
      {
        food_id: 207,
        food_name: "Zagorky",
        size: 2,
        weight: 100,
        energy: 100,
        water: 0,
        stomach: 0,
        locations: "Civilian",
        searchterms: ["chocolates", "dry goods"],
      },
      {
        food_id: 208,
        food_name: "Zagorky Chocolate",
        size: 2,
        weight: 100,
        energy: 200,
        water: 0,
        stomach: 0,
        locations: "Civilian",
        searchterms: ["chocolates", "dry goods"],
      },
      {
        food_id: 209,
        food_name: "Zagorky Peanuts",
        size: 2,
        weight: 100,
        energy: 150,
        water: 0,
        stomach: 0,
        locations: "Civilian",
        searchterms: ["chocolates", "dry goods"],
      },
    ],
  },
  {
    category_id: 3,
    category_name: "Fruits",
    foods: [
      {
        food_id: 301,
        food_name: "Apple",
        size: 1,
        weight: 125,
        energy: 100,
        water: 75,
        stomach: 1,
        locations: "Apple Trees",
        searchterms: ["fruits"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 10,
            water: 75,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 75,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 75,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 100,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 302,
        food_name: "Pear",
        size: 2,
        weight: 150,
        energy: 75,
        water: 50,
        stomach: 1,
        locations: "Pear Trees",
        searchterms: ["fruits"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 10,
            water: 50,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 300,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 250,
            water: 150,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 250,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 75,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 303,
        food_name: "Plum",
        size: 1,
        weight: 75,
        energy: 100,
        water: 75,
        stomach: 1,
        locations: "Plum Trees",
        searchterms: ["fruits"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 75,
            water: 50,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 300,
            water: 125,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 250,
            water: 175,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 250,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 125,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 304,
        food_name: "Tomato",
        size: 1,
        weight: 125,
        energy: 50,
        water: 100,
        stomach: 1,
        locations: "Obtained via Horticulture",
        searchterms: ["fruits", "dana white"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 150,
            water: 75,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 125,
            water: 100,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 125,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 5,
            water: 50,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 305,
        food_name: "Elderberries",
        size: 1,
        weight: 50,
        energy: 50,
        water: 80,
        stomach: 2.5,
        locations: "Sambucus Bushes",
        searchterms: ["fruits", "berry"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 37.5,
            water: 40,
            stomach: 2.5,
          },
          {
            variant_name: "Baked",
            energy: 90,
            water: 40,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 90,
            water: 80,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 90,
            water: 8,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 37.5,
            water: 20,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 306,
        food_name: "Rose Hips",
        size: 1,
        weight: 50,
        energy: 50,
        water: 80,
        stomach: 2.5,
        locations: "Canina Bushes",
        searchterms: ["fruits"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 37.5,
            water: 40,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 90,
            water: 40,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 90,
            water: 80,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 90,
            water: 8,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 37.5,
            water: 20,
            stomach: 2,
          },
        ],
      },
    ],
  },
  {
    category_id: 4,
    category_name: "Vegetables",
    foods: [
      {
        food_id: 401,
        food_name: "Pepper",
        size: 2,
        weight: 125,
        energy: 100,
        water: 50,
        stomach: 1,
        locations: "Obtained via Horticulture",
        searchterms: ["veggies", "vegetables"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 50,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 125,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 100,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 402,
        food_name: "Potato",
        size: 2,
        weight: 200,
        energy: 75,
        water: 25,
        stomach: 1,
        locations: "All locations",
        searchterms: ["veggies", "vegetables"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 50,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 25,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 1,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 75,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 403,
        food_name: "Pumpkin Slices",
        size: 6,
        weight: 200,
        energy: 75,
        water: 50,
        stomach: 1,
        locations: "Obtained from Pumpkins",
        searchterms: ["veggies", "vegetables"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 50,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 150,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 125,
            water: 100,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 125,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 75,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 404,
        food_name: "Zucchini",
        size: 3,
        weight: 200,
        energy: 125,
        water: 75,
        stomach: 1,
        locations: "Obtained via Horticulture",
        searchterms: ["veggies", "vegetables", "cucumber"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 75,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 150,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 125,
            water: 0,
            stomach: 5,
          },
        ],
      },
    ],
  },
  {
    category_id: 5,
    category_name: "Mushrooms",
    foods: [
      {
        food_id: 501,
        food_name: "Field Mushroom",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Haybales, Strawstacks",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 502,
        food_name: "Fly Amanita",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Coniferous forest, Deciduous forest",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 35,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 25,
            water: 95,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 20,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 503,
        food_name: "Liberty Cap",
        size: 1,
        weight: 50,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Haybales, Strawstacks",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 35,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 25,
            water: 95,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 20,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 504,
        food_name: "Oyster Mushroom",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Unknown",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 505,
        food_name: "Parasol Mushroom",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Coniferous forest",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 506,
        food_name: "Penny Bun",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Forest",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 507,
        food_name: "Red Pine Mushroom",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Deciduous forest",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
      {
        food_id: 508,
        food_name: "Wood ear",
        size: 2,
        weight: 150,
        energy: 20,
        water: 95,
        stomach: 2.5,
        locations: "Unknown",
        searchterms: ["mushrooms"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 47.5,
            stomach: 2,
          },
          {
            variant_name: "Baked",
            energy: 80,
            water: 71.25,
            stomach: 1.75,
          },
          {
            variant_name: "Boiled",
            energy: 60,
            water: 120,
            stomach: 1.5,
          },
          {
            variant_name: "Dried",
            energy: 30,
            water: 9.5,
            stomach: 0.75,
          },
          {
            variant_name: "Burned",
            energy: 15,
            water: 23.75,
            stomach: 2,
          },
        ],
      },
    ],
  },
  {
    category_id: 6,
    category_name: "Meat",
    foods: [
      {
        food_id: 601,
        food_name: "Bear Steak",
        size: 4,
        weight: 500,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Bear",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 400,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 350,
            water: 150,
            stomach: 2,
          },
          {
            variant_name: "Dried",
            energy: 350,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 602,
        food_name: "Boar Steak",
        size: 2,
        weight: 200,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Boar",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 325,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 275,
            water: 150,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 275,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 603,
        food_name: "Carp Fillet",
        size: 3,
        weight: 100,
        energy: 30,
        water: 60,
        stomach: 5,
        locations: "Obtained from a Carp",
        searchterms: ["fishes"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 15,
            water: 30,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 180,
            water: 60,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 150,
            water: 150,
            stomach: 2,
          },
          {
            variant_name: "Dried",
            energy: 120,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 30,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 604,
        food_name: "Chicken Steak",
        size: 2,
        weight: 125,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Hen and Rooster",
        searchterms: ["meats", "chicken breast"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 200,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 150,
            water: 100,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 150,
            water: 0,
            stomach: 2,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 605,
        food_name: "Cow Steak",
        size: 4,
        weight: 500,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Cow and Bull",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 300,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 250,
            water: 100,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 250,
            water: 0,
            stomach: 1,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 606,
        food_name: "Deer Steak",
        size: 2,
        weight: 200,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Doe, Roebuck, Hind and Stag",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 350,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 300,
            water: 100,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 300,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 607,
        food_name: "Goat Steak",
        size: 2,
        weight: 150,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Goat",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 150,
            stomach: 2,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 608,
        food_name: "Human Steak",
        size: 3,
        weight: 150,
        energy: 50,
        water: 50,
        stomach: 7,
        locations: "Obtained from a Survivor",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 200,
            water: 50,
            stomach: 4,
          },
          {
            variant_name: "Boiled",
            energy: 150,
            water: 150,
            stomach: 4,
          },
          {
            variant_name: "Dried",
            energy: 150,
            water: 0,
            stomach: 4,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 7,
          },
        ],
      },
      {
        food_id: 609,
        food_name: "Mackerel Fillet",
        size: 3,
        weight: 200,
        energy: 20,
        water: 40,
        stomach: 5,
        locations: "Obtained from a Mackerel",
        searchterms: ["fishes"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 10,
            water: 20,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 240,
            water: 40,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 160,
            water: 160,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 120,
            water: 0,
            stomach: 2,
          },
          {
            variant_name: "Burned",
            energy: 30,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 610,
        food_name: "Pig Steak",
        size: 2,
        weight: 200,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Pig",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 300,
            water: 50,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 250,
            water: 150,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 250,
            water: 0,
            stomach: 2,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 611,
        food_name: "Sheep Steak",
        size: 2,
        weight: 150,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from an Ewe or Ram",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 250,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 200,
            water: 100,
            stomach: 2,
          },
          {
            variant_name: "Dried",
            energy: 200,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 612,
        food_name: "Wolf Steak",
        size: 2,
        weight: 150,
        energy: 50,
        water: 50,
        stomach: 5,
        locations: "Obtained from a Wolf",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 25,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 200,
            water: 50,
            stomach: 2,
          },
          {
            variant_name: "Boiled",
            energy: 150,
            water: 150,
            stomach: 2,
          },
          {
            variant_name: "Dried",
            energy: 150,
            water: 0,
            stomach: 3,
          },
          {
            variant_name: "Burned",
            energy: 50,
            water: 0,
            stomach: 5,
          },
        ],
      },
      {
        food_id: 613,
        food_name: "Sardines",
        size: 2,
        weight: 110,
        energy: 20,
        water: 40,
        stomach: 5,
        locations: "Obtained from salt water (fishing)",
        searchterms: ["fishes"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 10,
            water: 20,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 100,
            water: 40,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 80,
            water: 80,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 80,
            water: 0,
            stomach: 2,
          },
          {
            variant_name: "Burned",
            energy: 20,
            water: 0,
            stomach: 1,
          },
        ],
      },
      {
        food_id: 614,
        food_name: "Bitterlings",
        size: 2,
        weight: 250,
        energy: 10,
        water: 20,
        stomach: 5,
        locations: "Obtained from fresh water (fishing)",
        searchterms: ["fishes"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 5,
            water: 10,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 50,
            water: 20,
            stomach: 1,
          },
          {
            variant_name: "Boiled",
            energy: 40,
            water: 40,
            stomach: 1,
          },
          {
            variant_name: "Dried",
            energy: 40,
            water: 0,
            stomach: 2,
          },
          {
            variant_name: "Burned",
            energy: 10,
            water: 0,
            stomach: 1,
          },
        ],
      },
    ],
  },
  {
    category_id: 7,
    category_name: "Drinks",
    foods: [
      {
        food_id: 701,
        food_name: "Soda Can",
        size: 2,
        weight: 15,
        energy: 50,
        water: 150,
        stomach: 1,
        locations: "All Locations",
        searchterms: [
          "water",
          "mad monk kvass",
          "nota cola",
          "pipsi cola",
          "spite lemonade",
          "fronta lemonade",
          "coca cola",
          "pepsi cola",
          "sprite lemonade",
          "fanta lemonade",
        ],
      },
    ],
  },
  {
    category_id: 8,
    category_name: "Others",
    foods: [
      {
        food_id: 801,
        food_name: "Fat",
        size: 4,
        weight: 200,
        energy: 100,
        water: 50,
        stomach: 7,
        locations: "Obtained from Animals and Survivors",
        searchterms: ["meats"],
        variants: [
          {
            variant_name: "Rotten",
            energy: 50,
            water: 25,
            stomach: 10,
          },
          {
            variant_name: "Baked",
            energy: 300,
            water: 50,
            stomach: 4,
          },
          {
            variant_name: "Boiled",
            energy: 250,
            water: 100,
            stomach: 4,
          },
          {
            variant_name: "Dried",
            energy: 250,
            water: 0,
            stomach: 5,
          },
          {
            variant_name: "Burned",
            energy: 100,
            water: 0,
            stomach: 7,
          },
        ],
      },
    ],
  },
];

export default FoodArray;
